services:
  # 1. The Laravel API
  - type: web
    name: beyondchats-api
    runtime: docker
    rootDir: laravel-api # <--- This tells Render the code is in the subfolder
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: beyondchats-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

  # 2. The React Frontend
  - type: web # Change to 'static' if you prefer a Static Site
    name: beyondchats-frontend
    runtime: node
    rootDir: react-frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run dev # Or 'npm run start' depending on your package.json
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: beyondchats-api
          property: host

databases:
  - name: beyondchats-db
    plan: free